### ISSUE TITLE
Fail when with hdf5 1.8.x

### ISSUE THREAD

**Issue by linboxi** [flexi-framework/hopr#2]
As I know, the CGNS-lib need hdf5 1.8.x to work correctly. But when build hopr with hdf5 1.8.x, the lib fails to write the output file.  Any corrections available?

**Comment by flexi-framework** [comment]
By default CGNS does not require HDF5. 
Did you build HOPR using the default settings or are you using self compiled libs? HOPR will by default build HDF5 1.10.0-patch1 and CGNS 3.2.1 itself, that should be straight forward. In that configuration the output of CGNS files works fine.
If you have a custom (self-built) CGNS lib, you will probably have to add the correct paths and make sure CGNS and HOPR are linked against the same HDF5 lib.

**Comment by linboxi** [comment]
The pintwise output cgns file in hdf5 format with szip decoder. So the default  build of hopr cannot work with the resulting file. The cgns lib works only with hdf5 1.8.x, so I build the hopr with cgns3.2.1, hdf5 1.8.13, szip ，and the link is correct. But the program  fails when read the cgns file.

**Comment by linboxi** [comment]
Sorry, there are some mistakes in last comment. The hopr fails in linking with hdf5 1.8.13 and cgns3.2.1. But when I build with cgnslib 3.2.1, hdf5 1.10.0 patch1, the link is correct, but fails in reading cgns files with pointwise output. I can read the same cgns correctly linking with  cgns3.2.1 hdf5 1.8.13 in my program, and fails too with cgns3.2.1 hdf5 1.10.0 patch1.

**Comment by linboxi** [comment]
All the build are with hdf5 support of cgnslib.

**Comment by flexi-framework** [comment]
Ok, now I'm a bit confused. Does HOPR fail when WRITING (as in your first post) or READING (as in the second post) a CGNS file. Since the interfaces of HDF5 changed with the switch from 1.8 to 1.10 HOPR will always require HDF5 1.10+.
In addition HOPR supports most but not all features of the CGNS standard, as various mesh generators produce vastly differing CGNS files. Writing CGNS files with HOPR should always work, whereas the reader might not support some configurations. Could you maybe upload a small sample file, which does not work (if the problem is reading CGNS)

**Comment by linboxi** [comment]
Sorry not to describe the problem concisely. 
The environment of my program is: Centos 6.4, with icc/ifort 15.0, mvapich2 2.0b. 

I want the cgnslib-3.2.1 with hdf5 support to read my cgns file outputted from Pointwise.

I build the cgnslib -3.2.1 with hdf5 1.10.0-patch1 support firstly and then link it correctly with HOPR. But the HOPR fails in **reading** cgns input file when use the agglomerates function.

In order to find the reason, I have built the cgnslib-3.2.1 with hdf5-1.8.13, and check the library correctness with in-house reader to the supplied cgns file. Then I build the cgnslib -3.2.1 with hdf5 1.10.0-patch1, and then the in-house reader fails to read the specific cgns file, thus prove the cgnslib-3.2.1 must with hdf5-1.8.13.

As you said, “since the interfaces of HDF5 changed with the switch from 1.8 to 1.10 HOPR will always require HDF5 1.10+”. The cgnslib-3.2.1 with hdf5-1.8.13 cannot be linked to the HOPR.

So, the problem is: the cgnslib-3.2.1 with hdf5 support cannot be used in the HOPR in the described case above. I wander if the HOPR can lower the HDF5 interface versions, or there are other solutions?

**Comment by linboxi** [comment]
How can I upload the file?

**Comment by linboxi** [comment]
[CGNS-parameter-.zip](https://github.com/flexi-framework/hopr/files/1047440/CGNS-parameter-.zip)

**Comment by flexi-framework** [comment]
[hopr_newcgns.tar.gz](https://github.com/flexi-framework/hopr/files/1048316/hopr_newcgns.tar.gz)

Here's an experimental patch, that enables support for CGNS 3.3, which is the first one supporting HDF5 1.10+. At the moment you need to build HDF5 yourself using CMake however and set the environment variable HDF5_DIR=path/to/hdf5/share/cmake 
I could open your file with this configuration, however there were some errors with the BC names in the parameter file you provided. Nevertheless opening and reading from CGNS files based on HDF5 works in this setting.
Pointwise should maybe have an option to enable the classic ADF mode for CGNS, which is what HOPR was using up to now.

**Comment by linboxi** [comment]
Thank you very much. 
I have tried the version you provided. I am sure that boundary condition and settings of my last supplied CGNS file are OK. And there are some problems in the CGNS 3.3 when reading the CGNS file, since the file is exported by CGNSLIB 3.14 and there are big differences in the low-level structure. The errors are listed as follows:
![cgns-error](https://cloud.githubusercontent.com/assets/11173020/26752543/10698798-4885-11e7-9a42-c676f95c68aa.png)
As you have mentioned, I try to use a program to transform the HDF5 Pointwise output file to ADF format. It works now.  
Thank you very much again.
