### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by XXXXThomas** [flexi-framework/hopr#4]
ubuntu 16.04  GNU compiler(CC=gcc FC=gfortran). Errors happens at the end of compiling work:

Scanning dependencies of target hoprlib
[ 97%] Linking Fortran static library lib/libhoprlib.a
[ 97%] Built target hoprlib
Scanning dependencies of target hopr
[ 98%] Building Fortran object CMakeFiles/hopr.dir/src/hopr.f90.o
[100%] Linking Fortran executable bin/hopr
lib/libhoprlib.a(globals.f90.o): In function `__mod_globals_MOD_getinverse':
globals.f90:(.text+0x127): undefined reference to `dgetrf_'
globals.f90:(.text+0x15e): undefined reference to `dgetri_'
lib/libhoprlib.a(basis1D.f90.o): In function `__mod_basis1d_MOD_inv':
basis1D.f90:(.text+0x2c5a): undefined reference to `dgetrf_'
basis1D.f90:(.text+0x2c88): undefined reference to `dgetri_'
collect2: error: ld returned 1 exit status
CMakeFiles/hopr.dir/build.make:103: recipe for target 'bin/hopr' failed
make[2]: *** [bin/hopr] Error 1
CMakeFiles/Makefile2:219: recipe for target 'CMakeFiles/hopr.dir/all' failed
make[1]: *** [CMakeFiles/hopr.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any suggestions about resolving the problem during the compiling process? Many thx.

**Comment by flexi-framework** [comment]
You need to have BLAS and LAPACK installed.
`sudo apt install libblas-dev liblapack-dev`
