### ISSUE TITLE
Build fails to install HDF5

### ISSUE THREAD

**Issue by avidalto** [flexi-framework/hopr#6]
Hello,

I am following the instructions in https://github.com/flexi-framework/hopr/blob/master/INSTALL.md and after running 

 `CC= FC= ccmake ../`

I get this error:

`[100%] Built target cgnscompress
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/lib/libcgns.a
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgnslib.h
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgns_io.h
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgnswin_f.h
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgnsconfig.h
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgnstypes.h
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgnstypes_f.h
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgnstypes_f03.h
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgnsBuild.defs
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/include/cgns.mod
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/bin/cgnscheck
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/bin/cgnsconvert
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/bin/cgnsdiff
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/bin/cgnslist
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/bin/cgnsnames
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/bin/cgnscompress
-- Installing: /opt/hopr-master/share/GNU-MPI/CGNS/build/build/bin/cgnsupdate
[ 11%] Completed 'cgns'
[ 11%] Built target cgns
Scanning dependencies of target hoprlibC
[ 12%] Building C object CMakeFiles/hoprlibC.dir/src/sfc/evalhilbert.c.o
[ 14%] Building C object CMakeFiles/hoprlibC.dir/src/sfc/hilbert.c.o
[ 14%] Built target hoprlibC
Scanning dependencies of target HDF5
[ 15%] Creating directories for 'HDF5'
[ 16%] Performing download step (git clone) for 'HDF5'
Cloning into 'HDF5'...
error: pathspec 'hdf5_1_10_4' did not match any file(s) known to git.
CMake Error at /opt/hopr-master/share/GNU-MPI/HDF5/build/tmp/HDF5-gitclone.cmake:65 (message):
  Failed to checkout tag: 'hdf5_1_10_4'

CMakeFiles/HDF5.dir/build.make:89: recipe for target '../share/GNU-MPI/HDF5/build/src/HDF5-stamp/HDF5-download' failed
make[2]: *** [../share/GNU-MPI/HDF5/build/src/HDF5-stamp/HDF5-download] Error 1
CMakeFiles/Makefile2:256: recipe for target 'CMakeFiles/HDF5.dir/all' failed
make[1]: *** [CMakeFiles/HDF5.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

It looks like cgns was successfully built but something breaks with hdf5. 

Thanks for your help!

**Comment by flexi-framework** [comment]
This was happening because the HDF5 repository changed the style of their tags that we try to check out during the build process. It should be fixed with the commit dded4a1fc42b386dc599decf1378b431221f29dc, please let us know if you still have problems.

Thanks for your contribution!
