### ISSUE TITLE
How to convert a high order GMsh to H5

### ISSUE THREAD

**Issue by alexxlzhou** [flexi-framework/hopr#8]
Hi,

I would like to use an existing high order GMsh file for simulations in flexi and I don't need additional curving with HOPR (assuming the high order mesh captured the curved boundary well).
To do that, I need to convert the mesh to the H5 format.
Is there a good way of example on how to do that?

I tried myself by creating a simple testing case of a 3D square (one layer in Z) with 2nd order Hex.
Both the parameter.ini and mesh files are attached at the end.
There are a few questions:
1) I used 
useCurveds=T
MeshIsAlreadyCurved=T
boundaryOrder=3
which seems to work but I don't understand why boundaryOrder is 3.
If I use useCurveds=F, I assume it will ouput the linear mesh only, right?

2) For the Z direction I want to use periodic boundary
BoundaryName=back              ! the BC_Name must be defined in mesh file
BoundaryType=(/1,1,0,1/)
BoundaryName=front              ! the BC_Name must be defined in mesh file
BoundaryType=(/1,1,0,-1/)
This will give errors like:
 Warning: Number of remaining nonconforming sides:           8
 Sides with missing connection found!
 Inner sides:            0  of            8  sides missing.
 Periodic sides            4  of            8  sides missing.
Program abort caused in File : src/mesh/mesh_connect.f90 Line          256
Message: Sides with missing connection found.

3) If I change that to non periodic bc, there will be no errors
BoundaryName=back              ! the BC_Name must be defined in mesh file
BoundaryType=(/2,1,0,0/)
BoundaryName=front              ! the BC_Name must be defined in mesh file
BoundaryType=(/2,1,0,0/)
Does the second number "1" (curveIndex) matter here, changing it to 0 works fine as well.

Thank you!

Alex

!=============================================================================== !
! OUTPUT
!=============================================================================== !
  projectname=square3d_q2             ! name of the project (used for filenames)
  Debugvisu    =T                  ! Write debug mesh to tecplot file
  outputFormat=1
  DebugVisuLevel=100
  checkElemJacobians=T
!=============================================================================== !
! MESH
!=============================================================================== !
Mode      =5                       ! 1 Cartesian 3 CGNS 4 STAR-CD V3 
Ngeo      =2
nZones    =1                     ! number of zones
filename=square3d_q2.msh
!=============================================================================== !
! CURVED
!=============================================================================== !
useCurveds=T                      ! T to generate curved boundaries 
MeshIsAlreadyCurved=T
boundaryOrder=3

!=============================================================================== !
! BOUNDARY CONDITIONS
!=============================================================================== !
BoundaryName=back              ! the BC_Name must be defined in mesh file
BoundaryType=(/1,1,0,1/)
BoundaryName=front              ! the BC_Name must be defined in mesh file
BoundaryType=(/1,1,0,-1/)
BoundaryName=bottom             ! the BC_Name must be defined in mesh file
BoundaryType=(/2,1,0,0/)
BoundaryName=right              ! the BC_Name must be defined in mesh file
BoundaryType=(/2,1,0,0/)
BoundaryName=top              ! the BC_Name must be defined in mesh file
BoundaryType=(/2,1,1,0/)
BoundaryName=left              ! the BC_Name must be defined in mesh file
BoundaryType=(/2,1,0,0/)

nVV=1
VV=(/0.,0.,1./)

!dummys,needed, do not change!
nVisu=1              
nAnalyze=1           

!=============================================================================== !
! GMsh file below
!=============================================================================== !

$MeshFormat
2.2 0 8
$EndMeshFormat
$PhysicalNames
7
2 1 "back"
2 2 "front"
2 3 "bottom"
2 4 "right"
2 5 "top"
2 6 "left"
3 7 "vol"
$EndPhysicalNames
$Nodes
75
1 0 -0 0
2 1 -0 0
3 1 1 0
4 0 1 0
5 1 1 0.1
6 0 1 0.1
7 0 0 0.1
8 1 0 0.1
9 0.4999999999986921 0 0
10 0.2499999999994184 0 0
11 0.7499999999993461 0 0
12 1 0.4999999999986921 0
13 1 0.2499999999994184 0
14 1 0.7499999999993461 0
15 0.5000000000020595 1 0
16 0.7500000000007601 1 0
17 0.2500000000010297 1 0
18 0 0.5000000000020595 0
19 0 0.7500000000007601 0
20 0 0.2500000000010297 0
21 0.5000000000020595 1 0.1
22 0.7500000000007601 1 0.1
23 0.2500000000010297 1 0.1
24 0 0.5000000000020595 0.1
25 0 0.7500000000007601 0.1
26 0 0.2500000000010297 0.1
27 0.4999999999986921 0 0.1
28 0.2499999999994184 0 0.1
29 0.7499999999993461 0 0.1
30 1 0.4999999999986921 0.1
31 1 0.2499999999994184 0.1
32 1 0.7499999999993461 0.1
33 1 1 0.04999999999985524
34 0 1 0.04999999999985524
35 0 0 0.04999999999985524
36 1 0 0.04999999999985524
37 0.5000000000003758 0.5000000000003758 0
38 0.4999999999995339 0.2500000000001879 0
39 0.2500000000001879 0.5000000000012177 0
40 0.2499999999998032 0.2500000000006088 0
41 0.5000000000012177 0.7500000000001878 0
42 0.2500000000006088 0.750000000000474 0
43 0.7500000000001878 0.4999999999995339 0
44 0.749999999999767 0.2499999999998032 0
45 0.750000000000474 0.749999999999767 0
46 0.5000000000020595 1 0.05
47 0.7500000000007601 1 0.04999999999992763
48 0.2500000000010296 1 0.04999999999992763
49 0 0.5000000000020595 0.05
50 0 0.7500000000007601 0.04999999999992763
51 0 0.2500000000010296 0.04999999999992763
52 0.4999999999986922 0 0.05
53 0.2499999999994185 0 0.04999999999992763
54 0.7499999999993461 0 0.04999999999992763
55 1 0.4999999999986922 0.05
56 1 0.2499999999994185 0.04999999999992763
57 1 0.7499999999993461 0.04999999999992763
58 0.5000000000003758 0.5000000000003758 0.1
59 0.4999999999995339 0.2500000000001879 0.1
60 0.2500000000001879 0.5000000000012177 0.1
61 0.2499999999998032 0.2500000000006088 0.1
62 0.5000000000012177 0.7500000000001878 0.1
63 0.2500000000006088 0.750000000000474 0.1
64 0.7500000000001878 0.4999999999995339 0.1
65 0.749999999999767 0.2499999999998032 0.1
66 0.750000000000474 0.749999999999767 0.1
67 0.5000000000003758 0.5000000000003758 0.05
68 0.499999999999534 0.2500000000001879 0.05
69 0.2500000000001879 0.5000000000012177 0.05
70 0.2499999999998032 0.2500000000006088 0.04999999999996381
71 0.5000000000012177 0.7500000000001878 0.05
72 0.2500000000006087 0.7500000000004741 0.0499999999999638
73 0.7500000000001878 0.499999999999534 0.05
74 0.7499999999997671 0.2499999999998032 0.0499999999999638
75 0.7500000000004741 0.7499999999997671 0.04999999999996381
$EndNodes
$Elements
20
1 10 2 1 1 1 9 37 18 10 38 39 20 40
2 10 2 1 1 18 37 15 4 39 41 17 19 42
3 10 2 1 1 9 2 12 37 11 13 43 38 44
4 10 2 1 1 37 12 3 15 43 14 16 41 45
5 10 2 3 13 3 15 21 5 16 46 22 33 47
6 10 2 3 13 15 4 6 21 17 34 23 46 48
7 10 2 4 17 4 18 24 6 19 49 25 34 50
8 10 2 4 17 18 1 7 24 20 35 26 49 51
9 10 2 5 21 1 9 27 7 10 52 28 35 53
10 10 2 5 21 9 2 8 27 11 36 29 52 54
11 10 2 6 25 2 12 30 8 13 55 31 36 56
12 10 2 6 25 12 3 5 30 14 33 32 55 57
13 10 2 2 26 7 27 58 24 28 59 60 26 61
14 10 2 2 26 24 58 21 6 60 62 23 25 63
15 10 2 2 26 27 8 30 58 29 31 64 59 65
16 10 2 2 26 58 30 5 21 64 32 22 62 66
17 12 2 7 1 1 9 37 18 7 27 58 24 10 20 35 38 52 39 67 49 28 26 59 60 40 53 51 68 69 61 70
18 12 2 7 1 18 37 15 4 24 58 21 6 39 19 49 41 67 17 46 34 60 25 62 23 42 69 50 71 48 63 72
19 12 2 7 1 9 2 12 37 27 8 30 58 11 38 52 13 36 43 55 67 29 59 31 64 44 54 68 56 73 65 74
20 12 2 7 1 37 12 3 15 58 30 5 21 43 41 67 14 55 16 33 46 64 62 32 22 45 73 71 57 47 66 75
$EndElements

**Comment by flexi-framework** [comment]
Hi Alex,
thanks for checking out FLEXI and HOPR. Unfortunately there is currently only a short abstract on using already curved meshes and Gmsh as input for HOPR. You can find some information on the [https://www.hopr-project.org/index.php/External_Meshes_with_Curved_Boundaries](hopr-project) website.

But now for the example:
1. Our definition of "BoundaryOrder" refers to the mathematical definition. So a constant approximation is of first order and a linear approximation is of second order. So a "typical" linear mesh is according to our definition of BoundaryOrder=2, and a curved high-order mesh with 3 points of BoundaryOrder=3. In Gmsh, the Order corresponds to the polynomial degree, while for us the Order=pol.degree+1.
2. You have to adapt the periodic displacement vector "vv" to your test case. This vector is needed to find and connect the periodic sides. In your example, the mesh has a thickness (and the periodic sides therefore a displacement) of 0.1 in z direction. If you adapt the periodic vector to the correct displacement
vv=(/0.,0.,0.1/)
the example runs fine for me. Could you please verify this?
3. You can drop the "1" since the second entry defines the "CurveIndex", which is only needed if hopr curves the mesh himself via the algorithms also described in the link given above.

I hope this resolves the questions. Good luck for your application,
The Flexi-Team

**Comment by alexxlzhou** [comment]
Great, thank you!
After your suggested changes, the input runs without a problem.
Just in case others may come around the same thing, below is the input after modification.

!=============================================================================== !
! OUTPUT
!=============================================================================== !
  projectname=square3d_q2             ! name of the project (used for filenames)
  Debugvisu    =T                  ! Write debug mesh to tecplot file
  outputFormat=1
  DebugVisuLevel=100
  checkElemJacobians=T
!=============================================================================== !
! MESH
!=============================================================================== !
Mode      =5                       ! 1 Cartesian 3 CGNS 4 STAR-CD V3 
Ngeo      =2
nZones    =1                     ! number of zones
filename=square3d_q2.msh
!=============================================================================== !
! CURVED
!=============================================================================== !
useCurveds=T                      ! T to generate curved boundaries 
MeshIsAlreadyCurved=T
boundaryOrder=3

!=============================================================================== !
! BOUNDARY CONDITIONS
!=============================================================================== !
BoundaryName=back              ! the BC_Name must be defined in mesh file
BoundaryType=(/1,0,0,1/)
BoundaryName=front              ! the BC_Name must be defined in mesh file
BoundaryType=(/1,0,0,-1/)
BoundaryName=bottom             ! the BC_Name must be defined in mesh file
BoundaryType=(/2,0,0,0/)
BoundaryName=right              ! the BC_Name must be defined in mesh file
BoundaryType=(/2,0,0,0/)
BoundaryName=top              ! the BC_Name must be defined in mesh file
BoundaryType=(/2,0,1,0/)
BoundaryName=left              ! the BC_Name must be defined in mesh file
BoundaryType=(/2,0,0,0/)

nVV=1
vv=(/0.,0.,0.1/) ! the displacement vector,see https://www.hopr-project.org/index.php/List_of_Parameters

!dummys,needed, do not change!
nVisu=1              
nAnalyze=1
